{
  "formatVersion": "1.1",
  "component": {
    "url": "../../maven-publish-test-sdk/1.0.6-fork/maven-publish-test-sdk-1.0.6-fork.module",
    "group": "org.example.project",
    "module": "maven-publish-test-sdk",
    "version": "1.0.6-fork",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mavenPublishTestSDK-release.aar",
          "url": "maven-publish-test-sdk-android-1.0.6-fork.aar",
          "size": 2539,
          "sha512": "860df9cde7588238b7c99cc084ee2f9b21e1fb639f73b1104aaf6bf373323ce076bc1ed785631b96f6416cc4623d32792189030f0621f796d684af8745cccf82",
          "sha256": "0b2f4a2a4556923a28879db518e7505e267b59afe91cff117023efda142737bf",
          "sha1": "e19730f38ae8606992b781386f4d34ec3dad7391",
          "md5": "c1eb20f625325f7e1c8ade60579c1929"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "mavenPublishTestSDK-release.aar",
          "url": "maven-publish-test-sdk-android-1.0.6-fork.aar",
          "size": 2539,
          "sha512": "860df9cde7588238b7c99cc084ee2f9b21e1fb639f73b1104aaf6bf373323ce076bc1ed785631b96f6416cc4623d32792189030f0621f796d684af8745cccf82",
          "sha256": "0b2f4a2a4556923a28879db518e7505e267b59afe91cff117023efda142737bf",
          "sha1": "e19730f38ae8606992b781386f4d34ec3dad7391",
          "md5": "c1eb20f625325f7e1c8ade60579c1929"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "mavenPublishTestSDK-android-1.0.6-fork-sources.jar",
          "url": "maven-publish-test-sdk-android-1.0.6-fork-sources.jar",
          "size": 1947,
          "sha512": "38a8a89f28a55b82b05265a4a0687c9a110e1527eb0849654522b8c8a2c65abbfc770fb500f00e67c2428f189c67ba3da8a87a89b032508c362eff4014cc9208",
          "sha256": "54f8b437e743870418b15d357349896623815683265611d8dc477edf8430533d",
          "sha1": "c1cca35748dcc6db8223708e39000ce8cb21633c",
          "md5": "c6058fef3005915780b780b46811e944"
        }
      ]
    }
  ]
}
